### ISSUE TITLE
Multi-dimensional arrays only partially supported

### ISSUE THREAD

**Issue by zhangkaihuo** [pgbovine/opt-cpp-backend#13]
my code:

```
#include<stdio.h>
int main(){
    int a[3][2] = {{1,2}, {2,3}, {3,4}};
    int i, j;
    for(i = 0; i < 3; i++){
        for(j = 0; j < 2; j++){
            printf("%d ", a[i][j]);
        }
        printf("\n");
    }
    return 0;
}
```

compile cmd:
gcc -std=c11 -ggdb -O0 -fno-omit-frame-pointer array4.c -o array4
../../opt-cpp-backend-master/valgrind-3.11.0/inst/bin/valgrind --tool=memcheck --source-filename=array4.c --trace-filename=array4.vgtrace ./array4 || true

faild:
==13626== Memcheck, a memory error detector
==13626== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==13626== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==13626== Command: ./array4
==13626== 

valgrind: m_debuginfo/tytypes.c:762 (vgModuleLocal_pg_pp_varinfo): Assertion 'VG_(sizeXA)(xa) == 1' failed.

host stacktrace:
==13626==    at 0x38085108: show_sched_status_wrk (m_libcassert.c:343)
==13626==    by 0x38085224: report_and_quit (m_libcassert.c:415)
==13626==    by 0x380853B1: vgPlain_assert_fail (m_libcassert.c:481)
==13626==    by 0x380CA4DD: vgModuleLocal_pg_pp_varinfo (tytypes.c:762)
==13626==    by 0x380B9849: vgPlain_pg_traverse_local_var (debuginfo.c:5149)
==13626==    by 0x3806AC15: pg_trace_inst.part.8 (mc_translate.c:6407)
==13626==    by 0x3806AE1F: pg_trace_inst (mc_translate.c:6274)
==13626==    by 0x8057E4DC8: ???
==13626==    by 0x80357DF2F: ???
==13626==    by 0x80200A46F: ???
==13626==    by 0x4005F5: ??? (in /home/zkh/Project/Code_Classify/src/src_array/array4)
==13626==    by 0x80200A46F: ???
==13626==    by 0x1BFF: ???

sched status:
  running_tid=1

Thread 1: status = VgTs_Runnable (lwpid 13626)
==13626==    at 0x4005F6: main (array4.c:2)

Note: see also the FAQ in the source distribution.
It contains workarounds to several common problems.
In particular, if Valgrind aborted or crashed after
identifying problems in your program, there's a good chance
that fixing those problems will prevent Valgrind aborting or
crashing, especially if it happened in m_mallocfree.c.

If that doesn't help, please report this bug to: www.valgrind.org

In the bug report, send all the above text, the valgrind
version, and what OS and version you are using.  Thanks.

Don't support a multidimensional array?
but two-dimensional pointer is ok.

**Comment by pgbovine** [comment]
Yes that is a known problem. Thank you for reporting!

**Comment by pgbovine** [comment]
Example:

```
    int main(int argc, char* argv[])
    {
    	int k,x[] = {2,0,4,1,3};
    	int y[4][4] = {{3,2,1,0},{3,1,0,2},{2,3,1,0},{0,1,2,3}};
     
    	k = x[2][x][x][x][x][x][x][x]; 
    	printf("%d", k);
     
    	k = y[2][2][y][2][2[y][2][y]];
    	printf("%d", k);
    	return 0;
    }
```

**Comment by pgbovine** [comment]
More examples:

```
int main(void) {
	int matrixA[2][3]={1, 2, 3, 4, 5, 6}; 
	int res[2][3]; 
	return 0;
}
```

```
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[])
{ 
int Matrix[10][10]; 
int x,y;

for(y=0;y<10;y++)
{
for(x=0;x<10;x++)
{ 
Matrix[y][x]=y*10+x+1; 
} 
}

for(y=0;y<10;y++)
{ 
for(x=0;x<10;x++)
{ 
printf("%3d ",Matrix[y][x]);
} 
printf("\n"); 
} 
return 0; 
}
```

**Comment by pgbovine** [comment]
a 2-D char array!

```
#include <stdlib.h>
#include<string.h>

int main() {
	char sentences[][100] = {"abc is a word","he he","   ","d ab   ","  x","asd324","","a"};
	char ans[][100] = { "word", "he","","ab","x","asd324","","a"};
	return 0;
}
```

**Comment by pgbovine** [comment]
It's now somewhat supported by flattening multi-dimensional arrays into 1-D arrays, but still not ideal
