### ISSUE TITLE
the execution efficiency of opt-cpp-backend

### ISSUE THREAD

**Issue by zhangkaihuo** [pgbovine/opt-cpp-backend#30]
Hello, there are two tracing tools,python and c, I am wondering the difference of the execution efficiency  between python and c. I have a test on c with your tools of c, there are 700 c code files, it costs over 20 minutes. However, the paper OverCode  have a test on python with your tools of python, there are 3000 python code files, it costs only 15 minutes. 
looking forward to your replying.

**Comment by pgbovine** [comment]
sorry this is off topic for this tool.
