### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by michaelmior** [pgbovine/opt-cpp-backend#32]
I'm intending on using this tool to provide students with visualizations of examples in a course I'm involved in here at the [University of Waterloo](https://uwaterloo.ca). I'd first like to make sure that this is acceptable use. If so, I want to ensure this project is properly credited. Would a link to the repo at the bottom of the page suffice?

**Comment by pgbovine** [comment]
Please link to www.pythontutor.com, thanks!
