### ISSUE TITLE
fork not working

### ISSUE THREAD

**Issue by tox123** [pgbovine/opt-cpp-backend#34]
This code just suddenly stops at the first if it finds. I think it has to do with the forking itself. You can see the code here: [http://www.pythontutor.com/c.html#code=%23include%20%3Cstdio.h%3E%0A%23include%20%3Cunistd.h%3E%0Atypedef%20int%20pid_t%3B%0A%0Aint%20main(int%20argc,%20char%20**argv%29%0A%7B%0A%20%20%20%20printf(%22--beginning%20of%20program%5Cn%22%29%3B%0A%0A%20%20%20%20int%20counter%20%3D%200%3B%0A%20%20%20%20pid_t%20pid%20%3D%20fork(%29%3B%0A%0A%20%20%20%20if%20(pid%20%3D%3D%200%29%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20//%20child%20process%0A%20%20%20%20%20%20%20%20int%20i%20%3D%200%3B%0A%20%20%20%20%20%20%20%20for%20(%3B%20i%20%3C%205%3B%20%2B%2Bi%29%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20printf(%22child%20process%3A%20counter%3D%25d%5Cn%22,%20%2B%2Bcounter%29%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20else%20if%20(pid%20%3E%200%29%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20//%20parent%20process%0A%20%20%20%20%20%20%20%20int%20j%20%3D%200%3B%0A%20%20%20%20%20%20%20%20for%20(%3B%20j%20%3C%205%3B%20%2B%2Bj%29%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20printf(%22parent%20process%3A%20counter%3D%25d%5Cn%22,%20%2B%2Bcounter%29%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20else%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20//%20fork%20failed%0A%20%20%20%20%20%20%20%20printf(%22fork(%29%20failed!%5Cn%22%29%3B%0A%20%20%20%20%20%20%20%20return%201%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20printf(%22--end%20of%20program--%5Cn%22%29%3B%0A%0A%20%20%20%20return%200%3B%0A%7D&mode=edit&origin=opt-frontend.js&py=c&rawInputLstJSON=%5B%5D](url)

**Comment by pgbovine** [comment]
fork is unlikely to be ever supported in this tool, sorry!
