### ISSUE TITLE
Incorrect trace output

### ISSUE THREAD

**Issue by michaelmior** [pgbovine/opt-cpp-backend#42]
When producing a trace on one system where there is a function call on the first line of the Makefile, the trace is missing a `call` event. This was working before and I also have it working on a different system. I'm using the same version of the code on both as well as the same major version of gcc. I know this is sparse on details, but if you have any ideas what could be causing this, that would be helpful as I do more digging.

**Comment by pgbovine** [comment]
can you let me know the C/C++ code that breaks? sorry it's hard to debug without details

**Comment by michaelmior** [comment]
No problem. I understand. Here's one example:

```C
int collatz(const int n) {
  if (n == 1) {
    return 1;
  } else if (n % 2 == 0) {
    return collatz(n / 2);
  } else {
    return collatz(3*n + 1);
  }
}

int main(void) {
  collatz(5);
}
```

I get the correct output on Ubuntu Trusty, but not on Xenial.

**Comment by pgbovine** [comment]
it works on the site itself https://goo.gl/EpKQ8e

so that's all i can support at the moment. sorry i can't test on other architectures other than the one on my server.

**Comment by michaelmior** [comment]
No problem. Totally understandable. I'll update here if I ever figure things out. (The architecture was x64 in both the failing and successful cases FYI.)
