### ISSUE TITLE
usercode.vgtrace Always Not Found

### ISSUE THREAD

**Issue by habibieeddien** [pgbovine/opt-cpp-backend#47]
Always stuck here: https://github.com/pgbovine/opt-cpp-backend/blob/master/vg_to_opt_trace.py#L230

when run this command line (from [run_cpp_backend.py](https://github.com/pgbovine/opt-cpp-backend/blob/master/run_cpp_backend.py#L54)):
`stdbuf -o0 valgrind --tool=memcheck --source-filename=./usercode.c --trace-filename=usercode.vgtrace ./usercode.exe`

the command `--trace-filename=usercode.vgtrace` is useless, still cannot produced `vgtrace` file

How do if upgrade to [Valgrind-3.12.0](http://valgrind.org/downloads/valgrind-3.12.0.tar.bz2) ?

**Comment by pgbovine** [comment]
You need to compile Valgrind inside the package first before running that script. hope that helps

**Comment by pgbovine** [comment]
do:

```
cd opt-cpp-backend/
make
```

**Comment by pgbovine** [comment]
running regular valgrind won't work. you need to run the custom-compiled valgrind inside of the repo, which is at: `valgrind-3.11.0/inst/bin/valgrind`. good luck!

**Comment by habibieeddien** [comment]
I have do `git clone` and then do:
`cd opt-cpp-backend/`
`make`

appear error like this:
`make[1]: Entering directory '/root/Documents/opt-cpp-backend/valgrind-3.11.0'`
`make[1]: *** No rule to make target 'install'.  Stop.`
`make[1]: Leaving directory '/root/Documents/opt-cpp-backend/valgrind-3.11.0'`
`Makefile:3: recipe for target 'all' failed`
`make: *** [all] Error 2`

What's wrong with this?

**Comment by habibieeddien** [comment]
Done.
I run this:
`./auto-everything.sh`

and then:
`python run_cpp_backend.py usercode.c c`
