### ISSUE TITLE
enum causing unknown error in C

### ISSUE THREAD

**Issue by Avantol13** [pgbovine/opt-cpp-backend#49]
[This code](https://goo.gl/HXSEuI) doesn't appear to work. The following is the code:
```
enum color 
{
  RED,
  ORANGE,
  YELLOW,
  GREEN,
  BLUE,
  INDIGO,
  VIOLET,
};

int main() {
  enum color my_color = RED;
  return 0;
}
```
Gives me this error after trying for a few seconds:

> Unknown error. Reload the page and try again. Or report a bug to
philip@pgbovine.net by clicking on the 'Generate permanent link'
button at the bottom and including a URL in your email.

**Comment by pgbovine** [comment]
yep, i'm getting on this soon :) thanks for the bug report. it doesn't support enums yet

**Comment by pgbovine** [comment]
fixed!

**Comment by Avantol13** [comment]
Sweet! Thank you!
