### ISSUE TITLE
More than 10 seconds Runtime required for C Codes

### ISSUE THREAD

**Issue by ramlaxman** [pgbovine/opt-cpp-backend#60]
Hi @pgbovine,
C program ,which is of just 21 lines, taking more than 10 seconds to run. After that it gives message that 
"Error: Your code ran for more than 15 seconds. The server may be overloaded right now. Please try again later, or shorten your code." Please extend server limit so that at least 50 lines of C program could execute.

**Comment by prateekchaplot** [comment]
Can you also post your code, so that suitable answer could be given

**Comment by pgbovine** [comment]
It's not a matter of lines of code, it's what your code contains. Also, sometimes the server is more busy than other times.
