### ISSUE TITLE
valgrind: Unknown option

### ISSUE THREAD

**Issue by nandu-deshmukh** [pgbovine/opt-cpp-backend#66]
I will try to run simple c code locally using this command.
<b>$ python run_cpp_backend.py "int main(){int a=10; return 0;}" c
</b>
valgrind: Unknown option: --source-filename=usercode.c
valgrind: Unknown option: --trace-filename=./usercode.vgtrace

And also not generated
=== postprocess stderr ===
Traceback (most recent call last):
  File "./vg_to_opt_trace.py", line 245, in <module>
    for line in open(basename + '.vgtrace'):
IOError: [Errno 2] No such file or directory: './usercode.vgtrace'

===
Please notify me how to solve this problem thanks.

**Comment by pgbovine** [comment]
Sorry I currently don't have time to document how to reproduce the valgrind backend workflow. Please refer to the code and existing documentation, or use the version hosted on pythontutor.com
